// background.js - Daisy Chrome Extension

const _api = chrome;

let dispatchEnabled = true;

// The Accumulator Maps
const capturedRequestHeaders  = new Map();
const capturedResponseHeaders = new Map();
const capturedCookies         = new Map();
const headerCacheTimestamps   = new Map();
const HEADER_CACHE_TTL_MS     = 15 * 60 * 1000; // 15 minute retention

// CRITICAL: Merge headers instead of overwriting, so we never lose
// X-Playback-Session-Id, Range, or Sec-Fetch headers across multiple sub-requests.
function mergeIntoMap(map, key, incomingData) {
    if (!key || typeof incomingData !== 'object') return;
    
    const existing = map.get(key) || {};
    const merged = { ...existing };
    
    for (const [k, v] of Object.entries(incomingData)) {
        if (v !== undefined && v !== null && v.toString().trim() !== "") {
            merged[k.toLowerCase()] = v;
        }
    }
    
    map.set(key, merged);
    headerCacheTimestamps.set(key, Date.now());
    
    for (const [k, ts] of headerCacheTimestamps) {
        if (Date.now() - ts > HEADER_CACHE_TTL_MS) {
            capturedRequestHeaders.delete(k);
            capturedResponseHeaders.delete(k);
            capturedCookies.delete(k);
            headerCacheTimestamps.delete(k);
        }
    }
}

_api.storage.local.get(["dispatchEnabled"]).then(res => {
    if (typeof res.dispatchEnabled === "boolean") dispatchEnabled = res.dispatchEnabled;
});

_api.storage.onChanged.addListener((changes, area) => {
    if (area === "local" && changes.dispatchEnabled) {
        dispatchEnabled = changes.dispatchEnabled.newValue;
        fetch(`http://127.0.0.1:6840/setenabled`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ enabled: changes.dispatchEnabled.newValue })
        }).catch(() => {});
    }
});

_api.runtime.onInstalled.addListener(() => {
    _api.contextMenus.create({ id: "dispatch-download", title: "Download with Daisy", contexts: ["link"] });
});

_api.contextMenus.onClicked.addListener((info, tab) => {
    if (info.menuItemId === "dispatch-download" && info.linkUrl) {
        triggerDownload(info.linkUrl, extractFilename(info.linkUrl), tab?.url || "");
    }
});

function extractFilename(url) {
    try {
        const parts = new URL(url).pathname.split("/");
        return decodeURIComponent(parts[parts.length - 1]) || "download";
    } catch { return "download"; }
}

function formatNetscapeCookies(cookies) {
    let output = "# Netscape HTTP Cookie File\n# Generated by Daisy\n\n";
    const unique = new Map();
    for (const c of cookies) unique.set(`${c.domain}:${c.name}`, c);
    for (const c of unique.values()) {
        const includeSubdoms = c.domain.startsWith('.') ? "TRUE" : "FALSE";
        const secure         = c.secure ? "TRUE" : "FALSE";
        const expiration     = c.expirationDate ? Math.round(c.expirationDate) : Math.round(Date.now() / 1000) + 3600;
        output += `${c.domain}\t${includeSubdoms}\t${c.path}\t${secure}\t${expiration}\t${c.name}\t${c.value}\n`;
    }
    return output;
}

function netscapeToCookieHeader(netscapeStr) {
    if (!netscapeStr || !netscapeStr.includes("\t")) return netscapeStr;
    const lines = netscapeStr.split("\n");
    const cookieParts = [];
    for (const line of lines) {
        if (line.startsWith("#") || line.trim() === "") continue;
        const tabs = line.split("\t");
        if (tabs.length >= 7) cookieParts.push(`${tabs[5]}=${tabs[6]}`);
    }
    return cookieParts.join("; ");
}

async function fetchBaseDomainCookies(targetUrl) {
    return new Promise(resolve => {
        try {
            const urlObj     = new URL(targetUrl);
            const hostParts  = urlObj.hostname.split('.');
            const baseDomain = hostParts.length > 2 ? hostParts.slice(-2).join('.') : urlObj.hostname;
            _api.cookies.getAll({ domain: baseDomain }, cookies => {
                resolve(cookies && cookies.length > 0 ? formatNetscapeCookies(cookies) : "");
            });
        } catch { resolve(""); }
    });
}

async function getYouTubeAuthCookies() {
    return new Promise(resolve => {
        _api.cookies.getAll({ domain: "youtube.com" }, yt => {
            _api.cookies.getAll({ domain: "google.com" }, gl => { resolve([...(yt || []), ...(gl || [])]); });
        });
    });
}

function lookupCookiesAggressively(url) {
    if (capturedCookies.has(url)) return capturedCookies.get(url);
    try {
        const origin = new URL(url).origin;
        if (capturedCookies.has(origin)) return capturedCookies.get(origin);
    } catch(_) {}
    return null;
}

_api.webRequest.onBeforeSendHeaders.addListener(
    function(details) {
        if (details.tabId === -1) return;
        const reqHeaders = {};
        for (const h of (details.requestHeaders || [])) reqHeaders[h.name.toLowerCase()] = h.value;
        
        mergeIntoMap(capturedRequestHeaders, details.url, reqHeaders);
        try {
            const urlObj = new URL(details.url);
            mergeIntoMap(capturedRequestHeaders, urlObj.origin, reqHeaders);
        } catch(_) {}

        fetchBaseDomainCookies(details.url).then(cookieStr => {
            if (cookieStr) mergeIntoMap(capturedCookies, details.url, cookieStr);
        });
    },
    { urls: ["<all_urls>"] },
    ["requestHeaders", "extraHeaders"]
);

_api.webRequest.onHeadersReceived.addListener(
    function(details) {
        if (details.tabId === -1) return;
        const respHeaders = {};
        for (const h of (details.responseHeaders || [])) respHeaders[h.name.toLowerCase()] = h.value;
        
        mergeIntoMap(capturedResponseHeaders, details.url, respHeaders);
        try {
            const urlObj = new URL(details.url);
            mergeIntoMap(capturedResponseHeaders, urlObj.origin, respHeaders);
        } catch(_) {}

        const ct = respHeaders["content-type"] || "";
        const isMedia = ["video/", "audio/", "mpegurl", "m3u8", "video/mp2t", "application/x-mpegurl", "application/vnd.apple.mpegurl", "application/dash+xml"].some(m => ct.includes(m));
        const urlLower = details.url.toLowerCase();
        const isMediaByUrl = ['.m3u8', '.ts', '.mp4', '.webm', '.mov', '.mkv', '/hls/', '/m3u8', 'manifest.m3u8', 'master.m3u8', '.mpd'].some(p => urlLower.includes(p));

        if (isMedia || isMediaByUrl) {
            _api.tabs.sendMessage(details.tabId, { type: 'NEW_MEDIA_FOUND', mediaInfo: { url: details.url, frameId: details.frameId } }).catch(() => {});
        }
    },
    { urls: ["<all_urls>"] },
    ["responseHeaders", "extraHeaders"]
);

_api.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === "PREPARE_DISPATCH_DOWNLOAD") {
        const pageUrl = sender.tab?.url || message.url || "";
        const finish = async () => {
            let cookiePayload = "";
            if (pageUrl.includes("youtube.com") || pageUrl.includes("youtu.be")) {
                const cookies = await getYouTubeAuthCookies();
                cookiePayload = cookies && cookies.length > 0 ? formatNetscapeCookies(cookies) : (message.cookies || "");
            } else {
                cookiePayload = lookupCookiesAggressively(message.url);
                if (!cookiePayload && pageUrl.startsWith("http")) cookiePayload = await fetchBaseDomainCookies(pageUrl);
                if (!cookiePayload) cookiePayload = message.cookies || "";
            }
            await triggerDownload(message.url, message.filename, sender.tab?.url || "", cookiePayload, message.youtubeQuality, message.forceHLS, message.forceDASH, message.pageHeaders || {});
        };

        finish().then(() => sendResponse({ success: true })).catch((e) => sendResponse({ success: false }));
        return true;
    }
});

async function triggerDownload(url, filename, referer, cookies, youtubeQuality, forceHLS, forceDASH, pageHeaders) {
    const capturedReqHeaders = capturedRequestHeaders.get(url) || (() => {
        try { return capturedRequestHeaders.get(new URL(url).origin) || {}; } catch(_) { return {}; }
    })();
    
    const capturedRespHeaders = capturedResponseHeaders.get(url) || (() => {
        try { return capturedResponseHeaders.get(new URL(url).origin) || {}; } catch(_) { return {}; }
    })();

    const mergedHeaders = Object.assign({}, pageHeaders || {}, capturedReqHeaders);
    if (referer && !mergedHeaders["referer"]) mergedHeaders["referer"] = referer;

    let finalCookies = cookies || lookupCookiesAggressively(url);
    if (finalCookies && !mergedHeaders["cookie"]) {
        mergedHeaders["cookie"] = netscapeToCookieHeader(finalCookies) || finalCookies;
    }

    const payload = JSON.stringify({
        url, filename: filename || "download", cookies: finalCookies || "", referer: mergedHeaders["referer"] || referer || "",
        ua: mergedHeaders["user-agent"] || navigator.userAgent,
        browser: "chrome",
        youtubeQuality, forceHLS, forceDASH,
        headers: mergedHeaders, responseHeaders: capturedRespHeaders,
        extraHeadersFlat: Object.entries(mergedHeaders).map(([k, v]) => `${k}: ${v}`).join("\n")
    });

    for (let port = 6840; port <= 6850; port++) {
        try {
            const resp = await fetch(`http://127.0.0.1:${port}/dispatch`, { method: "POST", headers: { "Content-Type": "application/json" }, body: payload });
            if (resp.ok) break;
        } catch (e) {}
    }
}
