// background.js - Daisy Chrome Extension

const _api = typeof browser !== "undefined" ? browser : chrome;
let dispatchEnabled = true;

const capturedRequestHeaders  = new Map();
const capturedResponseHeaders = new Map();
const capturedCookies         = new Map();
const headerCacheTimestamps   = new Map();
const HEADER_CACHE_TTL_MS     = 15 * 60 * 1000;

function mergeIntoMap(map, key, incomingData) {
    if (!key || typeof incomingData !== 'object') return;
    const existing = map.get(key) || {};
    const merged = { ...existing };
    for (const [k, v] of Object.entries(incomingData)) {
        if (v !== undefined && v !== null && v.toString().trim() !== "") {
            merged[k.toLowerCase()] = v;
        }
    }
    map.set(key, merged);
    headerCacheTimestamps.set(key, Date.now());
    
    for (const [k, ts] of headerCacheTimestamps) {
        if (Date.now() - ts > HEADER_CACHE_TTL_MS) {
            capturedRequestHeaders.delete(k); capturedResponseHeaders.delete(k);
            capturedCookies.delete(k); headerCacheTimestamps.delete(k);
        }
    }
}

function getCapturedHeaders(map, targetUrl) {
    if (!targetUrl) return {};
    if (map.has(targetUrl)) return map.get(targetUrl);
    try {
        const u = new URL(targetUrl);
        const withoutQuery = u.origin + u.pathname;
        if (map.has(withoutQuery)) return map.get(withoutQuery);
        if (map.has(u.origin)) return map.get(u.origin);
    } catch(_) {}
    return {};
}

function cleanMediaUrl(urlStr) {
    try {
        const u = new URL(urlStr);
        u.searchParams.delete('bytestart');
        u.searchParams.delete('byteend');
        u.searchParams.delete('range');
        return u.toString();
    } catch { return urlStr; }
}

_api.storage.local.get(["dispatchEnabled"]).then(res => {
    if (typeof res.dispatchEnabled === "boolean") dispatchEnabled = res.dispatchEnabled;
});

_api.storage.onChanged.addListener((changes, area) => {
    if (area === "local" && changes.dispatchEnabled) {
        dispatchEnabled = changes.dispatchEnabled.newValue;
        fetch(`http://127.0.0.1:6840/setenabled`, {
            method: "POST", headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ enabled: changes.dispatchEnabled.newValue })
        }).catch(() => {});
    }
});

_api.runtime.onInstalled.addListener(() => {
    _api.contextMenus.create({ id: "dispatch-download", title: "Download with Daisy", contexts: ["link"] });
});

_api.contextMenus.onClicked.addListener((info, tab) => {
    if (info.menuItemId === "dispatch-download" && info.linkUrl) {
        triggerDownload(info.linkUrl, extractFilename(info.linkUrl), tab?.url || "");
    }
});

_api.downloads.onCreated.addListener(async (downloadItem) => {
    if (!dispatchEnabled) return;
    
    const targetUrl = downloadItem.finalUrl || downloadItem.url;
    if ((targetUrl || "").startsWith("blob:") || (targetUrl || "").startsWith("data:")) return;

    _api.downloads.cancel(downloadItem.id, () => {
        setTimeout(() => _api.downloads.erase({ id: downloadItem.id }, () => {}), 150);
    });

    let fname = "download";
    if (downloadItem.filename) {
        const parts = downloadItem.filename.split(/[/\\]/);
        fname = parts[parts.length - 1];
    } else {
        fname = extractFilename(targetUrl);
    }

    let cookies = lookupCookiesAggressively(targetUrl);
    if (!cookies && targetUrl.startsWith("http")) cookies = await fetchBaseDomainCookies(targetUrl);

    triggerDownload(targetUrl, fname, downloadItem.referrer || "", cookies, null, false, false, { "referer": downloadItem.referrer || "" });
});

function extractFilename(url) {
    try {
        const parts = new URL(url).pathname.split("/");
        return decodeURIComponent(parts[parts.length - 1]) || "download";
    } catch { return "download"; }
}

function formatNetscapeCookies(cookies) {
    let output = "# Netscape HTTP Cookie File\n# Generated by Daisy\n\n";
    const unique = new Map();
    for (const c of cookies) unique.set(`${c.domain}:${c.name}`, c);
    for (const c of unique.values()) {
        const includeSubdoms = c.domain.startsWith('.') ? "TRUE" : "FALSE";
        const secure         = c.secure ? "TRUE" : "FALSE";
        const expiration     = c.expirationDate ? Math.round(c.expirationDate) : Math.round(Date.now() / 1000) + 3600;
        output += `${c.domain}\t${includeSubdoms}\t${c.path}\t${secure}\t${expiration}\t${c.name}\t${c.value}\n`;
    }
    return output;
}

function netscapeToCookieHeader(netscapeStr) {
    if (!netscapeStr || !netscapeStr.includes("\t")) return netscapeStr;
    const lines = netscapeStr.split("\n");
    const cookieParts = [];
    for (const line of lines) {
        if (line.startsWith("#") || line.trim() === "") continue;
        const tabs = line.split("\t");
        if (tabs.length >= 7) cookieParts.push(`${tabs[5]}=${tabs[6]}`);
    }
    return cookieParts.join("; ");
}

async function fetchBaseDomainCookies(targetUrl) {
    return new Promise(resolve => {
        try {
            const urlObj = new URL(targetUrl);
            const hostParts = urlObj.hostname.split('.');
            const baseDomain = hostParts.length > 2 ? hostParts.slice(-2).join('.') : urlObj.hostname;
            _api.cookies.getAll({ domain: baseDomain }, cookies => {
                resolve(cookies && cookies.length > 0 ? formatNetscapeCookies(cookies) : "");
            });
        } catch { resolve(""); }
    });
}

async function getYouTubeAuthCookies() {
    return new Promise(resolve => {
        _api.cookies.getAll({ domain: "youtube.com" }, yt => {
            _api.cookies.getAll({ domain: "google.com" }, gl => { resolve([...(yt || []), ...(gl || [])]); });
        });
    });
}

function lookupCookiesAggressively(url) {
    if (capturedCookies.has(url)) return capturedCookies.get(url);
    try {
        const origin = new URL(url).origin;
        if (capturedCookies.has(origin)) return capturedCookies.get(origin);
    } catch(_) {}
    return null;
}

_api.webRequest.onBeforeSendHeaders.addListener(
    function(details) {
        if (details.url.includes("127.0.0.1:684")) return;
        const reqHeaders = {};
        for (const h of (details.requestHeaders || [])) reqHeaders[h.name.toLowerCase()] = h.value;
        
        mergeIntoMap(capturedRequestHeaders, details.url, reqHeaders);
        try {
            const u = new URL(details.url);
            mergeIntoMap(capturedRequestHeaders, u.origin + u.pathname, reqHeaders);
            mergeIntoMap(capturedRequestHeaders, u.origin, reqHeaders);
        } catch(_) {}

        fetchBaseDomainCookies(details.url).then(cookieStr => {
            if (cookieStr) mergeIntoMap(capturedCookies, details.url, cookieStr);
        });
    },
    { urls: ["<all_urls>"] },
    ["requestHeaders", "extraHeaders"]
);

const IGNORABLE_EXTS = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.svg', '.css', '.js', '.woff', '.woff2', '.ttf', '.eot', '.ico'];

_api.webRequest.onHeadersReceived.addListener(
    function(details) {
        if (details.url.includes("127.0.0.1:684")) return;
        if (details.type !== 'xmlhttprequest' && details.type !== 'media' && details.type !== 'fetch') return;

        const urlLower = details.url.toLowerCase();
        const urlWithoutQuery = urlLower.split('?')[0];
        
        if (IGNORABLE_EXTS.some(ext => urlWithoutQuery.endsWith(ext))) return;

        const respHeaders = {};
        for (const h of (details.responseHeaders || [])) respHeaders[h.name.toLowerCase()] = h.value;
        
        mergeIntoMap(capturedResponseHeaders, details.url, respHeaders);
        try {
            const u = new URL(details.url);
            mergeIntoMap(capturedResponseHeaders, u.origin + u.pathname, respHeaders);
            mergeIntoMap(capturedResponseHeaders, u.origin, respHeaders);
        } catch(_) {}

        let mediaType = 'unknown';
        const ct = (respHeaders["content-type"] || "").toLowerCase();
        
        // Strictly evaluate obfuscated anime/social URLs without fetching payload (preserves single-use tokens)
        if (urlLower.includes('bytestart=')) {
            mediaType = 'mp4';
        } else if (ct.includes('mpegurl') || ct.includes('m3u8') || urlLower.includes('/m3/') || urlLower.includes('/hls/')) {
            mediaType = 'hls';
        } else if (ct.includes('dash+xml') || urlLower.includes('/dash/')) {
            mediaType = 'dash';
        } else if (ct.includes('video/mp4') || ct.includes('video/webm')) {
            mediaType = 'mp4';
        }

        const isMedia = mediaType !== 'unknown' || ct.includes('video/') || ct.includes('audio/');
        const isMediaByUrl = ['.m3u8', '.ts', '.mp4', '.webm', '.mov', '.mkv', '/hls/', '/m3u8', '/m3/', '/dash/', 'manifest.m3u8', 'master.m3u8', '.mpd'].some(p => urlLower.includes(p));

        if (isMedia || isMediaByUrl) {
            // Drop raw spam segments
            if (urlLower.includes('.ts') && !urlLower.includes('.m3u8')) return;
            if (ct.includes('video/mp2t')) return;

            const finalUrl = cleanMediaUrl(details.url);
            const payload = { type: 'NEW_MEDIA_FOUND', mediaInfo: { url: finalUrl, frameId: details.frameId, mediaType: mediaType } };

            if (details.tabId !== -1) {
                _api.tabs.sendMessage(details.tabId, payload).catch(() => {});
            } else {
                _api.tabs.query({ active: true, currentWindow: true }, (tabs) => {
                    if (tabs && tabs.length > 0) _api.tabs.sendMessage(tabs[0].id, payload).catch(() => {});
                });
            }
        }
    },
    { urls: ["<all_urls>"] },
    ["responseHeaders", "extraHeaders"]
);

_api.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === "FETCH_MANIFEST") {
        fetch(message.url, { credentials: 'include' })
            .then(r => r.ok ? r.text() : Promise.reject(r.status))
            .then(text => sendResponse({ ok: true, text }))
            .catch(err => sendResponse({ ok: false }));
        return true;
    }
    if (message.type === "PREPARE_DISPATCH_DOWNLOAD") {
        const pageUrl = sender.tab?.url || message.url || "";
        const finish = async () => {
            let cookiePayload = "";
            if (pageUrl.includes("youtube.com") || pageUrl.includes("youtu.be")) {
                const cookies = await getYouTubeAuthCookies();
                cookiePayload = cookies && cookies.length > 0 ? formatNetscapeCookies(cookies) : (message.cookies || "");
            } else {
                cookiePayload = lookupCookiesAggressively(message.url);
                if (!cookiePayload && pageUrl.startsWith("http")) cookiePayload = await fetchBaseDomainCookies(pageUrl);
                if (!cookiePayload) cookiePayload = message.cookies || "";
            }
            await triggerDownload(message.url, message.filename, sender.tab?.url || "", cookiePayload, message.youtubeQuality, message.forceHLS, message.forceDASH, message.pageHeaders || {});
        };
        finish().then(() => sendResponse({ success: true })).catch(() => sendResponse({ success: false }));
        return true;
    }
});

async function triggerDownload(url, filename, referer, cookies, youtubeQuality, forceHLS, forceDASH, pageHeaders) {
    const capturedReqHeaders = getCapturedHeaders(capturedRequestHeaders, url);
    const capturedRespHeaders = getCapturedHeaders(capturedResponseHeaders, url);

    const mergedHeaders = Object.assign({}, pageHeaders || {}, capturedReqHeaders);
    if (referer && !mergedHeaders["referer"]) mergedHeaders["referer"] = referer;
    if (!mergedHeaders["user-agent"]) mergedHeaders["user-agent"] = navigator.userAgent;

    let finalCookies = cookies || lookupCookiesAggressively(url);
    if (!finalCookies && url.startsWith("http")) finalCookies = await fetchBaseDomainCookies(url);

    if (finalCookies && !mergedHeaders["cookie"]) mergedHeaders["cookie"] = netscapeToCookieHeader(finalCookies) || finalCookies;

    const payload = JSON.stringify({
        url, filename: filename || "download", cookies: finalCookies || "", referer: mergedHeaders["referer"] || referer || "",
        ua: mergedHeaders["user-agent"], browser: "chrome", youtubeQuality, forceHLS, forceDASH,
        headers: mergedHeaders, responseHeaders: capturedRespHeaders,
        extraHeadersFlat: Object.entries(mergedHeaders).map(([k, v]) => `${k}: ${v}`).join("\n")
    });

    for (let port = 6840; port <= 6850; port++) {
        try {
            const resp = await fetch(`http://127.0.0.1:${port}/dispatch`, { method: "POST", headers: { "Content-Type": "application/json" }, body: payload });
            if (resp.ok) break;
        } catch (e) {}
    }
}
