// background.js - Daisy Chrome & Safari Extension

const _api = typeof browser !== "undefined" ? browser : chrome;

let dispatchEnabled = true;
let bypassGraceUntil = 0;

const capturedRequestHeaders  = new Map();
const capturedResponseHeaders = new Map();
const capturedCookies         = new Map();
const headerCacheTimestamps   = new Map();
const HEADER_CACHE_TTL_MS     = 5 * 60 * 1000;

function storeWithTTL(map, key, value) {
    if (!key) return;
    map.set(key, value);
    headerCacheTimestamps.set(key, Date.now());
    for (const [k, ts] of headerCacheTimestamps) {
        if (Date.now() - ts > HEADER_CACHE_TTL_MS) {
            capturedRequestHeaders.delete(k);
            capturedResponseHeaders.delete(k);
            capturedCookies.delete(k);
            headerCacheTimestamps.delete(k);
        }
    }
}

function findCapturedDataAggressive(map, targetUrl) {
    let merged = {};
    if (!targetUrl) return merged;
    
    try {
        const tUrl = new URL(targetUrl);
        const tPath = tUrl.pathname;
        const tBase = tUrl.origin + tPath;

        for (const [key, val] of map.entries()) {
            try {
                const kUrl = new URL(key);
                if (kUrl.hostname === tUrl.hostname || kUrl.hostname.includes(tUrl.hostname) || tUrl.hostname.includes(kUrl.hostname)) {
                    if (key === targetUrl || key === tBase || tUrl.origin === key || kUrl.origin === targetUrl) {
                        Object.assign(merged, val);
                    } else if (tPath.length > 5 && (key.includes(tPath) || targetUrl.includes(key))) {
                        Object.assign(merged, val);
                    }
                }
            } catch(e) {}
        }
    } catch(e) {
        if (map.has(targetUrl)) Object.assign(merged, map.get(targetUrl));
    }
    return merged;
}

function findCapturedCookieAggressive(targetUrl) {
    if (!targetUrl) return "";
    if (capturedCookies.has(targetUrl)) return capturedCookies.get(targetUrl);
    try {
        const u = new URL(targetUrl);
        if (capturedCookies.has(u.origin)) return capturedCookies.get(u.origin);
        for (const [key, val] of capturedCookies.entries()) {
            if (key.includes(u.hostname)) return val;
        }
    } catch(e) {}
    return "";
}

_api.storage.local.get(["dispatchEnabled"]).then(res => {
    if (typeof res.dispatchEnabled === "boolean") dispatchEnabled = res.dispatchEnabled;
});

_api.storage.onChanged.addListener((changes, area) => {
    if (area === "local" && changes.dispatchEnabled) {
        dispatchEnabled = changes.dispatchEnabled.newValue;
        fetch(`http://127.0.0.1:6840/setenabled`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ enabled: changes.dispatchEnabled.newValue })
        }).catch(() => {});
    }
});

_api.runtime.onInstalled.addListener(() => {
    _api.contextMenus.create({
        id: "dispatch-download",
        title: "Download with Daisy",
        contexts: ["link", "selection", "video", "audio"]
    });
});

_api.contextMenus.onClicked.addListener((info, tab) => {
    if (info.menuItemId === "dispatch-download") {
        const targetUrl = info.linkUrl || info.srcUrl || info.selectionText;
        if (targetUrl) {
            triggerDownload(targetUrl, extractFilename(targetUrl), tab?.url || "");
        }
    }
});

function extractFilename(url) {
    try {
        const parts = new URL(url).pathname.split("/");
        return decodeURIComponent(parts[parts.length - 1]) || "download";
    } catch { return "download"; }
}

/**
 * Parse a Content-Disposition header value and return a filename.
 * Prefers the RFC 5987 `filename*=UTF-8''encoded` variant over the
 * legacy `filename=` variant because servers that send both (Claude,
 * S3, Google Cloud, Dropbox, ...) use the starred form for the real
 * name and the unstarred form as an ASCII fallback.
 */
function parseDispositionFilename(cd) {
    if (!cd) return null;
    const star = cd.match(/filename\*\s*=\s*([^;]+)/i);
    if (star && star[1]) {
        let raw = star[1].trim().replace(/^["']|["']$/g, '');
        // Strip `charset''` prefix (e.g. UTF-8'' or ISO-8859-1'').
        const sep = raw.indexOf("''");
        if (sep !== -1) raw = raw.slice(sep + 2);
        try { return decodeURIComponent(raw); } catch { return raw; }
    }
    const plain = cd.match(/filename\s*=\s*("([^"]*)"|([^;]+))/i);
    if (plain) {
        const raw = (plain[2] || plain[3] || '').trim();
        try { return decodeURIComponent(raw); } catch { return raw; }
    }
    return null;
}

function formatNetscapeCookies(cookies) {
    let output = "# Netscape HTTP Cookie File\n# Generated by Daisy\n\n";
    const unique = new Map();
    for (const c of cookies) unique.set(`${c.domain}:${c.name}`, c);
    for (const c of unique.values()) {
        const includeSubdoms = c.domain.startsWith('.') ? "TRUE" : "FALSE";
        const secure         = c.secure ? "TRUE" : "FALSE";
        const expiration     = c.expirationDate ? Math.round(c.expirationDate) : Math.round(Date.now() / 1000) + 3600;
        output += `${c.domain}\t${includeSubdoms}\t${c.path}\t${secure}\t${expiration}\t${c.name}\t${c.value}\n`;
    }
    return output;
}

async function fetchBaseDomainCookies(targetUrl) {
    return new Promise(resolve => {
        try {
            const urlObj     = new URL(targetUrl);
            const hostParts  = urlObj.hostname.split('.');
            const baseDomain = hostParts.length > 2 ? hostParts.slice(-2).join('.') : urlObj.hostname;
            _api.cookies.getAll({ domain: baseDomain }, cookies => {
                resolve(cookies && cookies.length > 0 ? formatNetscapeCookies(cookies) : "");
            });
        } catch { resolve(""); }
    });
}

async function getYouTubeAuthCookies() {
    return new Promise(resolve => {
        _api.cookies.getAll({ domain: "youtube.com" }, yt => {
            _api.cookies.getAll({ domain: "google.com" }, gl => { resolve([...(yt || []), ...(gl || [])]); });
        });
    });
}

const reqExtraInfo = ["requestHeaders"];
if (_api.webRequest && _api.webRequest.OnBeforeSendHeadersOptions && _api.webRequest.OnBeforeSendHeadersOptions.hasOwnProperty('EXTRA_HEADERS')) {
    reqExtraInfo.push("extraHeaders");
}

_api.webRequest.onBeforeSendHeaders.addListener(
    function(details) {
        const reqHeaders = {};
        for (const h of (details.requestHeaders || [])) reqHeaders[h.name.toLowerCase()] = h.value;
        
        storeWithTTL(capturedRequestHeaders, details.url, reqHeaders);
        try {
            const u = new URL(details.url);
            storeWithTTL(capturedRequestHeaders, u.origin + u.pathname, reqHeaders);
            storeWithTTL(capturedRequestHeaders, u.origin, reqHeaders);
        } catch(_) {}

        fetchBaseDomainCookies(details.url).then(cookieStr => {
            if (cookieStr) storeWithTTL(capturedCookies, details.url, cookieStr);
        });
    },
    { urls: ["<all_urls>"] },
    reqExtraInfo
);

const resExtraInfo = ["responseHeaders"];
if (_api.webRequest && _api.webRequest.OnHeadersReceivedOptions && _api.webRequest.OnHeadersReceivedOptions.hasOwnProperty('EXTRA_HEADERS')) {
    resExtraInfo.push("extraHeaders");
}

// Tracks URLs we've already routed through Daisy in the recent past so that
// `webRequest.onHeadersReceived` (which fires when the server emits the
// download response) and `downloads.onCreated` (which fires when the
// browser starts the native download a moment later) don't both
// dispatch the same file. The window has to comfortably outlive the
// gap between those two events on slow networks.
const recentDispatchedUrls = new Map();
const DISPATCH_DEDUP_MS = 15000;

function markDispatched(url) {
    if (!url) return;
    recentDispatchedUrls.set(url, Date.now());
    // Drop entries older than the dedup window so the map doesn't grow
    // unboundedly during a long-lived background-page session.
    const cutoff = Date.now() - DISPATCH_DEDUP_MS;
    for (const [u, ts] of recentDispatchedUrls) {
        if (ts < cutoff) recentDispatchedUrls.delete(u);
    }
}

function wasRecentlyDispatched(url) {
    if (!url) return false;
    const ts = recentDispatchedUrls.get(url);
    if (!ts) return false;
    return (Date.now() - ts) < DISPATCH_DEDUP_MS;
}

_api.webRequest.onHeadersReceived.addListener(
    function(details) {
        const respHeaders = {};
        for (const h of (details.responseHeaders || [])) respHeaders[h.name.toLowerCase()] = h.value;
        
        storeWithTTL(capturedResponseHeaders, details.url, respHeaders);
        try {
            const u = new URL(details.url);
            storeWithTTL(capturedResponseHeaders, u.origin + u.pathname, respHeaders);
            storeWithTTL(capturedResponseHeaders, u.origin, respHeaders);
        } catch(_) {}

        const ct = respHeaders["content-type"] || "";
        const isMedia = ["video/", "audio/", "mpegurl", "m3u8", "video/mp2t", "application/x-mpegurl", "application/vnd.apple.mpegurl", "application/dash+xml", "application/xml", "text/xml"].some(m => ct.includes(m));
        const urlLower = details.url.toLowerCase();
        const isMediaByUrl = ['.m3u8', '.ts', '.mp4', '.webm', '.mov', '.mkv', '/hls/', '/m3u8', 'manifest.m3u8', 'master.m3u8', '.mpd', '/dash/', 'dashplaylist', 'dash.xml', '/manifest', 'video.ism', 'application/dash', '/stream/', 'playlist', 'quality=', 'bitrate=', 'resolution='].some(p => urlLower.includes(p));

        if ((isMedia || isMediaByUrl) && details.tabId !== -1) {
            _api.tabs.sendMessage(details.tabId, { type: 'NEW_MEDIA_FOUND', mediaInfo: { url: details.url, frameId: details.frameId } }, { frameId: 0 }).catch(() => {});
            if (details.frameId !== 0) {
                _api.tabs.sendMessage(details.tabId, { type: 'NEW_MEDIA_FOUND', mediaInfo: { url: details.url, frameId: details.frameId } }, { frameId: details.frameId }).catch(() => {});
            }
        }

        // ---- Generic download safety net ----
        // Any time a server returns Content-Disposition: attachment on a
        // top-level navigation (or an iframe load), the browser will
        // cancel the navigation and start a native download. On Chrome
        // we also catch that via `downloads.onCreated`, but Safari's
        // implementation of that event has historically been flaky for
        // navigations triggered by a link click, programmatic
        // `location.href` assignment, hidden-iframe tricks, or
        // server-issued attachments without a recognizable filename
        // extension. By dispatching directly here we cover those
        // cases — the dedup map keeps `downloads.onCreated` from
        // re-dispatching the same URL.
        const cd = respHeaders["content-disposition"] || "";
        const isAttachment = cd.toLowerCase().includes("attachment");
        const isNavigationType = details.type === "main_frame" || details.type === "sub_frame";
        if (
            isAttachment &&
            isNavigationType &&
            dispatchEnabled &&
            Date.now() >= bypassGraceUntil &&
            details.tabId !== -1 &&
            !wasRecentlyDispatched(details.url) &&
            !details.url.startsWith("blob:") &&
            !details.url.startsWith("data:")
        ) {
            markDispatched(details.url);
            const filenameFromCD = parseDispositionFilename(cd);

            (async () => {
                let referer = "";
                try {
                    const tab = await _api.tabs.get(details.tabId);
                    if (tab && tab.url) referer = tab.url;
                } catch (_) {}
                const filename = filenameFromCD || extractFilename(details.url);
                triggerDownload(details.url, filename, referer, null, null, false, false, {});
            })();
        }
    },
    { urls: ["<all_urls>"] },
    resExtraInfo
);

// --- SAFARI & CHROME NATIVE DOWNLOAD INTERCEPTOR ---
if (_api.downloads && typeof _api.downloads.onCreated !== 'undefined') {
    _api.downloads.onCreated.addListener((item) => {
        if (!dispatchEnabled) return;
        
        if (Date.now() < bypassGraceUntil) {
            bypassGraceUntil = 0;
            return;
        }
        
        if (item.url.startsWith("blob:") || item.url.startsWith("data:")) return;

        // The webRequest CD-attachment branch above may have already
        // dispatched this URL. We still need to cancel/erase the native
        // download item so Safari doesn't end up writing to disk in
        // parallel with Daisy.
        const alreadyDispatched = wasRecentlyDispatched(item.url);
        if (!alreadyDispatched) markDispatched(item.url);

        const finishCancel = () => {
            if (alreadyDispatched) return;
            triggerDownload(item.url, item.filename, item.referrer || "", null, null, false, false, {});
        };

        try {
            _api.downloads.cancel(item.id).then(() => {
                _api.downloads.erase({id: item.id}).catch(()=>{});
                finishCancel();
            }).catch(()=>{});
        } catch (e) {
            if (_api.downloads.cancel) {
                _api.downloads.cancel(item.id, () => {
                    _api.downloads.erase({id: item.id}, () => {});
                    finishCancel();
                });
            }
        }
    });
}

_api.runtime.onMessage.addListener((message, sender, sendResponse) => {

    if (message.type === "PREFLIGHT_LINK") {
        // Credentials must be included — many app endpoints (Claude,
        // Gmail, Drive, private S3) only return a Content-Disposition
        // header for authenticated requests. Without this the HEAD
        // request comes back as a 401 redirect and we end up with no
        // filename.
        fetch(message.url, { method: "HEAD", redirect: "follow", credentials: "include" })
            .then(res => {
                const cd = res.headers.get('content-disposition') || '';
                const ct = res.headers.get('content-type') || '';
                let isDownload = false;
                let filename = parseDispositionFilename(cd);

                if (cd.toLowerCase().includes('attachment')) {
                    isDownload = true;
                } else {
                    const mediaTypes = ['application/octet-stream', 'video/', 'audio/', 'application/pdf', 'application/zip', 'application/x-rar-compressed', 'application/x-apple-diskimage'];
                    if (mediaTypes.some(t => ct.toLowerCase().includes(t))) isDownload = true;
                }
                sendResponse({ isDownload, filename });
            })
            .catch(() => sendResponse({ isDownload: false, filename: null }));
        return true;
    }

    if (message.type === "SET_BYPASS_GRACE") {
        bypassGraceUntil = Date.now() + 60000;
        sendResponse({ ok: true });
        return true;
    }

    if (message.type === "PUSH_MEDIA_HEADERS") {
        if (message.headers && typeof message.headers === "object") {
            for (const [url, headers] of Object.entries(message.headers)) {
                if (!url || typeof headers !== "object") continue;
                const existing = capturedRequestHeaders.get(url) || {};
                const merged = Object.assign({}, headers, existing);
                storeWithTTL(capturedRequestHeaders, url, merged);
                try {
                    const u = new URL(url);
                    storeWithTTL(capturedRequestHeaders, u.origin + u.pathname, Object.assign({}, headers, capturedRequestHeaders.get(u.origin + u.pathname) || {}));
                    storeWithTTL(capturedRequestHeaders, u.origin, Object.assign({}, headers, capturedRequestHeaders.get(u.origin) || {}));
                } catch(_) {}
            }
        }
        sendResponse({ ok: true });
        return true;
    }

    if (message.type === "FETCH_MANIFEST") {
        const reqHeaders = findCapturedDataAggressive(capturedRequestHeaders, message.url);
        fetch(message.url, { headers: reqHeaders })
            .then(r => r.text())
            .then(text => sendResponse({ ok: true, text: text }))
            .catch(e => sendResponse({ ok: false }));
        return true;
    }

    if (message.type === "PREPARE_DISPATCH_DOWNLOAD") {
        const pageUrl = sender.tab?.url || message.url || "";
        const finish = async () => {
            if (pageUrl.includes("youtube.com") || pageUrl.includes("youtu.be")) {
                const cookies = await getYouTubeAuthCookies();
                const cookiePayload = cookies && cookies.length > 0 ? formatNetscapeCookies(cookies) : (message.cookies || "");
                await triggerDownload(message.url, message.filename, sender.tab?.url || "", cookiePayload, message.youtubeQuality, message.forceHLS, message.forceDASH, message.pageHeaders || {});
            } else {
                let cookiePayload = findCapturedCookieAggressive(message.url);
                if (!cookiePayload && pageUrl.startsWith("http")) cookiePayload = await fetchBaseDomainCookies(pageUrl);
                if (!cookiePayload) cookiePayload = message.cookies || "";
                await triggerDownload(message.url, message.filename, sender.tab?.url || "", cookiePayload, message.youtubeQuality, message.forceHLS, message.forceDASH, message.pageHeaders || {});
            }
        };

        finish().then(() => sendResponse({ success: true })).catch((e) => sendResponse({ success: false }));
        return true;
    }
});

async function triggerDownload(url, filename, referer, cookies, youtubeQuality, forceHLS, forceDASH, pageHeaders) {
    let finalCookies = cookies;
    if (!finalCookies) finalCookies = findCapturedCookieAggressive(url) || await fetchBaseDomainCookies(referer || url);
    
    const reqHeaders  = findCapturedDataAggressive(capturedRequestHeaders, url);
    const respHeaders = findCapturedDataAggressive(capturedResponseHeaders, url);
    
    const mergedHeaders = Object.assign({}, pageHeaders || {}, reqHeaders);
    if (referer && !mergedHeaders["referer"]) mergedHeaders["referer"] = referer;

    const payload = JSON.stringify({
        url, filename: filename || "download", cookies: finalCookies || "", referer: referer || "",
        ua: navigator.userAgent, browser: "safari/chrome", youtubeQuality, forceHLS, forceDASH,
        headers: mergedHeaders,
        requestHeaders: mergedHeaders,
        responseHeaders: respHeaders,
        extraHeadersFlat: Object.entries(mergedHeaders).map(([k, v]) => `${k}: ${v}`).join("\n")
    });

    for (let port = 6840; port <= 6850; port++) {
        try {
            const resp = await fetch(`http://127.0.0.1:${port}/dispatch`, { method: "POST", headers: { "Content-Type": "application/json" }, body: payload });
            if (resp.ok) break;
        } catch (e) {}
    }
}
