// background.js - Daisy Safari Extension

let dispatchEnabled = true;
let bypassNextDownloadUrl = null;

// Safari uses browser namespace instead of chrome
const api = typeof browser !== 'undefined' ? browser : chrome;

api.storage.local.get(["dispatchEnabled"]).then(res => {
    if (typeof res.dispatchEnabled === "boolean") dispatchEnabled = res.dispatchEnabled;
});

api.storage.onChanged.addListener((changes, area) => {
    if (area === "local" && changes.dispatchEnabled) {
        dispatchEnabled = changes.dispatchEnabled.newValue;
    }
});

// Safari compatibility: context menus need to be created differently
api.runtime.onInstalled.addListener(() => {
    try {
        api.contextMenus.create({
            id: "dispatch-download",
            title: "Download with Daisy",
            contexts: ["link"]
        });
    } catch (e) {
        console.log("Context menu creation failed in Safari:", e);
    }
});

api.contextMenus.onClicked.addListener((info, tab) => {
    if (info.menuItemId === "dispatch-download" && info.linkUrl) {
        triggerDownload(info.linkUrl, extractFilename(info.linkUrl), tab?.url || "");
    }
});

function extractFilename(url) {
    try {
        const parts = new URL(url).pathname.split("/");
        return decodeURIComponent(parts[parts.length - 1]) || "download";
    } catch { return "download"; }
}

function needsCredentialedFetch(url) {
    try { return /claude\.ai$/.test(new URL(url).hostname); } catch { return false; }
}

// Safari doesn't fully support onDeterminingFilename, use downloads.onCreated as fallback
if (api.downloads && api.downloads.onDeterminingFilename) {
    api.downloads.onDeterminingFilename.addListener((item, suggest) => {
        if (!dispatchEnabled) return;
        const url = item.finalUrl || item.url;
        
        if (!url || url.startsWith("blob:") || url.startsWith("data:") || bypassNextDownloadUrl === url) {
            bypassNextDownloadUrl = null;
            return;
        }

        api.downloads.cancel(item.id);

        const referer = item.referrer || "";
        const filename = item.filename ? item.filename.split(/[\/\\]/).pop() : extractFilename(url);

        if (needsCredentialedFetch(url)) {
            api.tabs.query({ active: true, currentWindow: true }).then(tabs => {
                const tabId = tabs?.[0]?.id;
                if (tabId) {
                    api.tabs.sendMessage(tabId, { type: "CREDENTIALED_FETCH", url, filename })
                        .catch(() => triggerDownload(url, filename, referer));
                }
            });
        } else {
            triggerDownload(url, filename, referer);
        }
        return true;
    });
}

function formatNetscapeCookies(cookies) {
    let output = "# Netscape HTTP Cookie File\n# Generated by Daisy\n\n";
    let uniqueCookies = new Map();
    for (let c of cookies) {
        uniqueCookies.set(`${c.domain}:${c.name}`, c);
    }
    for (let c of uniqueCookies.values()) {
        let domain = c.domain;
        let includeSubdomains = domain.startsWith('.') ? "TRUE" : "FALSE";
        let path = c.path;
        let secure = c.secure ? "TRUE" : "FALSE";
        let expiration = c.expirationDate ? Math.round(c.expirationDate) : Math.round(Date.now() / 1000) + 3600;
        output += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${c.name}\t${c.value}\n`;
    }
    return output;
}

async function fetchBaseDomainCookies(targetUrl) {
    return new Promise(resolve => {
        try {
            let urlObj = new URL(targetUrl);
            let hostParts = urlObj.hostname.split('.');
            let baseDomain = hostParts.length > 2 ? hostParts.slice(-2).join('.') : urlObj.hostname;
            
            api.cookies.getAll({ domain: baseDomain }, cookies => {
                if (cookies && cookies.length > 0) {
                    resolve(formatNetscapeCookies(cookies));
                } else {
                    resolve("");
                }
            });
        } catch {
            resolve("");
        }
    });
}

async function getYouTubeAuthCookies() {
    return new Promise(resolve => {
        api.cookies.getAll({ domain: "youtube.com" }, yt => {
            api.cookies.getAll({ domain: "google.com" }, gl => {
                resolve([...(yt || []), ...(gl || [])]);
            });
        });
    });
}

api.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === "PREPARE_DISPATCH_DOWNLOAD") {
        let pageUrl = sender.tab?.url || message.url || "";

        if (pageUrl.includes("youtube.com") || pageUrl.includes("youtu.be")) {
            getYouTubeAuthCookies().then(cookies => {
                let cookiePayload = message.cookies || "";
                if (cookies && cookies.length > 0) {
                    cookiePayload = formatNetscapeCookies(cookies);
                }
                triggerDownload(message.url, message.filename, sender.tab?.url || "", cookiePayload, message.youtubeQuality, message.forceHLS);
            });
        } else {
            if (pageUrl.startsWith("http")) {
                fetchBaseDomainCookies(pageUrl).then(fetchedCookies => {
                    let cookiePayload = message.cookies || fetchedCookies;
                    triggerDownload(message.url, message.filename, sender.tab?.url || "", cookiePayload, message.youtubeQuality, message.forceHLS);
                });
            } else {
                triggerDownload(message.url, message.filename, sender.tab?.url || "", message.cookies || "", message.youtubeQuality, message.forceHLS);
            }
        }
        sendResponse({ success: true });
        return true;
    }
});

async function getHostBrowser() {
    // Safari detection
    const isSafari = navigator.userAgent.includes('Safari') && !navigator.userAgent.includes('Chrome');
    if (isSafari) return "safari";
    
    if (navigator.brave && await navigator.brave.isBrave()) return "brave";
    if (navigator.userAgentData && navigator.userAgentData.brands) {
        const brands = navigator.userAgentData.brands.map(b => b.brand.toLowerCase());
        if (brands.some(b => b.includes("edge"))) return "edge";
        if (brands.some(b => b.includes("opera") || b.includes("opr"))) return "opera";
        if (brands.some(b => b.includes("vivaldi"))) return "vivaldi";
        if (brands.some(b => b.includes("chrome"))) return "chrome";
        if (brands.some(b => b.includes("chromium"))) return "chromium";
    }
    if (typeof browser !== 'undefined' && browser.runtime?.getBrowserInfo) return "firefox";
    if (isSafari) return "safari";
    return "chrome";
}

async function triggerDownload(url, filename, referer, cookies, youtubeQuality, forceHLS) {
    let finalCookies = cookies;
    if (!finalCookies) {
        finalCookies = await fetchBaseDomainCookies(referer || url);
    }

    const extBrowser = await getHostBrowser();
    const payload = JSON.stringify({
        url, filename: filename || "download", cookies: finalCookies || "",
        referer: referer || "", ua: navigator.userAgent, browser: extBrowser,
        youtubeQuality, forceHLS
    });
    
    let success = false;
    for (let port = 6840; port <= 6850; port++) {
        try {
            const resp = await fetch(`http://127.0.0.1:${port}/dispatch`, {
                method: "POST", headers: { "Content-Type": "application/json" }, body: payload
            });
            if (resp.ok) { success = true; break; }
        } catch (_) {}
    }

    if (!success && !url.startsWith('data:')) {
        bypassNextDownloadUrl = url;
        if (api.downloads && api.downloads.download) {
            api.downloads.download({ url: url, filename: filename || undefined });
        } else {
            // Safari fallback: open in new tab
            api.tabs.create({ url: url, active: false });
        }
    }
}

// Safari webRequest support is limited, use alternative approach
if (api.webRequest && api.webRequest.onHeadersReceived) {
    api.webRequest.onHeadersReceived.addListener(
        function(details) {
            if (details.tabId === -1) return;
            const targetMimeTypes = ["video/", "audio/", "mpegurl", "m3u8", "video/mp2t", "application/x-mpegurl", "application/vnd.apple.mpegurl"];
            const isMedia = details.responseHeaders?.some(h =>
                h.name.toLowerCase() === "content-type" && targetMimeTypes.some(m => h.value.toLowerCase().includes(m))
            );
            const urlLower = details.url.toLowerCase();
            const isMediaByUrl = ['.m3u8', '.ts', '.mp4', '.webm', '.mov', '.mkv', '/hls/', '/m3u8', 'manifest.m3u8'].some(p => urlLower.includes(p));

            if (isMedia || isMediaByUrl) {
                api.tabs.sendMessage(
                    details.tabId,
                    { type: 'NEW_MEDIA_FOUND', mediaInfo: { url: details.url, frameId: details.frameId } },
                    { frameId: 0 }
                ).catch(() => {});
                
                if (details.frameId !== 0) {
                    api.tabs.sendMessage(
                        details.tabId,
                        { type: 'NEW_MEDIA_FOUND', mediaInfo: { url: details.url, frameId: details.frameId } },
                        { frameId: details.frameId }
                    ).catch(() => {});
                }
            }
        },
        { urls: ["<all_urls>"] },
        ["responseHeaders"]
    );
}
